name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "icook.tw"
    port: 8880
    uuid: "aa7461af-3176-42a3-8974-59930189c521"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "round-block-e864.326.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "hk200m.jiasu.asia"
    port: 50000
    password: "b5772a33-e151-4afa-b59c-7a7696f4819c"
    sni: "hk200m.jiasu.asia"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
  - name: "@rossinna77Github"
    type: vless
    server: "141.101.120.73"
    port: 443
    uuid: "5d8eb33a-2166-4daf-88fe-4be5799c493b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "noisy-term-e657.airdrop2014aa5168.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "noisy-term-e657.airdrop2014aa5168.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "45.85.88.194"
    port: 2234
    password: "tripitropa994825"
    sni: "vps.tropicalhosting.net"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "xstack.mahanfixe.workers.dev"
    port: 443
    uuid: "a8b1d666-d3ba-4b17-90c4-ba7514c74f78"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xstack.mahanfixe.workers.dev"
    network: ws
    ws-opts:
      path: "/xiron"
  - name: "@rossinna77Github"
    type: vless
    server: "skk.moe"
    port: 8880
    uuid: "f32b0ea8-5b9f-4ee2-b20c-0bdfd2057e1d"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "throbbing-shape-b190.478-57a.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.135.235.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime07.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "sg4-r.link-t7.com"
    port: 10039
    uuid: "F2987FBA-B653-444D-8057-6B6474E448C6"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "d1.awsstatic.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "wOu-BMrXvk9KX23JZrlpUlF4SMjDcejm0vNECdhy5xE"
      short-id: "686c0ef0"
    network: grpc
    grpc-opts:
      grpc-service-name: "update"
  - name: "@rossinna77Github"
    type: vless
    server: "172.67.174.37"
    port: 8880
    uuid: "2efeba50-78fe-4729-9821-1fb9819ed9e8"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "dark-dew-c3ed.48-97c.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.23.72"
    port: 8880
    uuid: "1b3ad465-d37e-48a2-bb53-d7fddfc97b11"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "calm-silence-d4a1.217.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.16.99.215"
    port: 8880
    uuid: "23187ddc-16a5-432d-bf4e-dd42a7ae39f7"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "steep-thunder-97fa.108-d10.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "38.180.186.202"
    port: 443
    uuid: "237f5460-66a2-4c27-97e6-93b352733a3a"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "zvukipro.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.23.72"
    port: 8880
    uuid: "942bdcfc-e522-44f1-b899-3bd8db7c5ae2"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "winter-leaf-b4da.122-6c9.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "round-block-e864.326.workers.dev"
    port: 8880
    uuid: "aa7461af-3176-42a3-8974-59930189c521"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
  - name: "@rossinna77Github"
    type: vless
    server: "www.glassdoor.com"
    port: 8880
    uuid: "f6e14309-5cff-4f5d-bce1-06a260159bbe"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "steep-bread-32f0.92-d12.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "joostkleinserver.net"
    port: 443
    uuid: "6eb642a2-f8ee-47cc-9c13-fabb0a50350d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "joostkleinserver.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/api/v1/stream"
  - name: "@rossinna77Github"
    type: trojan
    server: "165.215.250.14"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "//assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@rossinna77Github"
    type: vless
    server: "v5p.sabermusic.ir"
    port: 443
    uuid: "eaeb9077-b90c-45e3-a52c-da847f5f86d7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v5p.sabermusic.ir"
  - name: "@rossinna77Github"
    type: vless
    server: "104.19.46.223"
    port: 443
    uuid: "103744ce-0153-49b1-2eac-d293a6ddd7e2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nahan-mouse-7749.amirsina2026.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "nahan-mouse-7749.amirsina2026.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "13.212.45.128"
    port: 12322
    uuid: "a2d84cff-5a0f-4559-b793-355d363a4738"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AG7GDrwsSNOf3mXfGVRSKBwszQFJ_QDxqQPHlyN-HAw"
      short-id: "5b89483cf98148"
  - name: "@rossinna77Github"
    type: vless
    server: "104.18.46.234"
    port: 80
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "200.165.234.119"
    port: 4100
    uuid: "099f0859-cb81-4a57-b6d8-2c8e18030627"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "@rossinna77Github"
    type: vless
    server: "51.158.206.12"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
  - name: "@rossinna77Github"
    type: vless
    server: "188.114.98.0"
    port: 80
    uuid: "08e3dc8c-596a-4f4c-97ce-b6e3b93cd949"
    udp: true
    network: ws
    ws-opts:
      path: "/zFZcAUY4pA8W4r26"
      headers:
        Host: "worker3.wocayir177.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "5.152.223.192"
    port: 443
    uuid: "222e1ff7-4145-4116-ad85-06ce0ab6eb92"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "strapi.io"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
  - name: "@rossinna77Github"
    type: vless
    server: "78.129.150.110"
    port: 443
    uuid: "671193bf-3203-487a-82bf-9a160ee30254"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "strapi.io"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY"
      short-id: "fd55b698ee8c3629"
  - name: "@rossinna77Github"
    type: vless
    server: "www.zsu.gov.ua"
    port: 8880
    uuid: "bfa3aaaf-41d3-4ec4-8453-e9827d7e7b30"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "crimson-mode-f8de.432-9e1.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "104.21.16.123"
    port: 443
    password: "Telegram_healer_config"
    sni: "7X7o3VTq5z6ymu3Hv1fH-Op9BlT.hYa6LOSM6lZNOXHm6w3MK.woRKErS.DeV"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/tr/qL8YIeH28wNcXfNTPgLCwOhNFEr?ed=2560"
      headers:
        Host: "7x7o3vtq5z6ymu3hv1fh-op9blt.hya6losm6lznoxhm6w3mk.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "64.188.59.203"
    port: 443
    uuid: "ae2009b9-76cb-4d18-8612-7515b2b84398"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tg1.wba-pn.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
