name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "54.178.110.17"
    port: 4443
    uuid: "d5fbd83b-7346-4ad9-94c0-76293724824d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "95.85.231.231"
    port: 42321
    uuid: "7412605e-18de-4b34-af4e-82e9f544cc24"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "C8lo017EXpVnG_TxCYibs_NBzbgoW-61IQH4qZhHGmw"
      short-id: "3f080f861d7f"
  - name: "@rossinna77Github"
    type: vless
    server: "144.31.76.198"
    port: 13443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "auto.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
  - name: "@rossinna77Github"
    type: vless
    server: "courses.zigapacademy.ir"
    port: 2053
    uuid: "50414e45-4c5f-5a45-5553-60c86b8747e5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web-app-aug8yr.app-f1qsy1.workers.dev"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/api/ws"
      headers:
        Host: "web-app-aug8yr.app-f1qsy1.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "144.124.248.186"
    port: 443
    uuid: "40de6299-d792-4868-8a82-411ead0aa943"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "gateway.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "L0acYoTxKR5ix7LXAmP10cy06n2JjgkXTojGjtWAqww"
      short-id: "ed7b9bdfedb9b8e5"
  - name: "@rossinna77Github"
    type: trojan
    server: "lucky-chimp.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "lucky-chimp.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "5c31ca5d-0094-4a7e-a06e-7f2ce96e44db"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.146.129"
    port: 8880
    uuid: "11046a7c-fa1b-4653-ab87-400feb465540"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net@https://t.me/QiangLieTuiJian"
      headers:
        Host: "nameless-poetry-12fb.8-0a2.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.24.143.217"
    port: 443
    uuid: "50414e45-4c5f-5a45-5553-4eef5adc237a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "r5zenrelur2s.pqzdileiu8es.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/stream/PANEL_ZEUS/4eef5adc237a/loc-1"
      headers:
        Host: "r5zenrelur2s.pqzdileiu8es.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "185.132.125.163"
    port: 443
    uuid: "7b102311-43fd-4e8f-877e-8090623c101d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vp10.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vp10.pages.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "classic-pug.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "classic-pug.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "188.114.97.6"
    port: 8880
    uuid: "d7ec3e31-a9c4-4bdf-a2d8-7f75a8381035"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "weathered-lake-e883.35-bc4.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "2c.fast9988.com"
    port: 50887
    password: "6ec301428255a78a1d826988d86cc87e"
    sni: "www.nintendogames.net"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
