name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: trojan
    server: "104.18.114.47"
    port: 443
    password: "MiTiVPN"
    sni: "PioHosting.ir"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/MiTiVPN=NL"
      headers:
        Host: "PioHosting.ir"
  - name: "@rossinna77Github"
    type: vless
    server: "104.16.106.213"
    port: 8880
    uuid: "82a3c394-55b7-4780-93a0-5f45c0e89625"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "square-brook-e650.353-3ac.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.19.53"
    port: 8080
    uuid: "d682c8f4-e719-577e-cbe9-2e5b00000003"
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "0406.infinityconfig7.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.82.226"
    port: 443
    uuid: "36a857e4-f3d4-43aa-8b90-d7da849da989"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "002.Inc-ElectROcElL-001-002.WoRKERS.DEV"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoib0RnakxTZUZvOSIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "002.inc-electrocell-001-002.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.76.194.232"
    port: 443
    uuid: "eeb6823c-b926-4ea2-866a-5542edd26e59"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "t1s1.rittbo.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "t1s1.rittbo.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "168.138.165.174"
    port: 443
    uuid: "eeb6823c-b926-4ea2-866a-5542edd26e59"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "t1s1.rittbo.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "t1s1.rittbo.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "104.17.147.22"
    port: 443
    uuid: "a4d78557-9173-f6de-0670-cb6397766acf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mayan.bahbah9595.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/mayan"
      headers:
        Host: "mayan.bahbah9595.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "162.159.156.214"
    port: 8880
    uuid: "25322a43-4ef3-45cc-9e96-db44bcccd7be"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "purple-disk-f68d.14-360.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "104.16.72.41"
    port: 8880
    uuid: "28201cd6-c2a9-4703-a31b-eaf31ecb18fd"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip"
      headers:
        Host: "summer-butterfly-cbc8.26-971.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "112.121.184.10"
    port: 26057
    uuid: "970ffe5a-2c53-4b94-af3f-c95ddd417c1c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "videos.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ipkmPcrX6VD4_cB3kS4DigWSP9FcU6TPXpkWM5m-jEw"
      short-id: "e4fb5619"
  - name: "@rossinna77Github"
    type: vless
    server: "72.167.243.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime55.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "64.186.235.57"
    port: 443
    password: "eeb6823c-b926-4ea2-866a-5542edd26e59"
    sni: "tjsp.hhxaf.cc.cd"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "tjsp.hhxaf.cc.cd"
  - name: "@rossinna77Github"
    type: trojan
    server: "104.18.7.147"
    port: 443
    password: "humanity"
    sni: "www.gossipglove.com"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.gossipglove.com"
  - name: "@rossinna77Github"
    type: vless
    server: "nuclear.us.kg"
    port: 443
    uuid: "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nuclear.us.kg"
    network: ws
    ws-opts:
      path: "/free/1.226.227.169:50001"
      headers:
        Host: "nuclear.us.kg"
  - name: "@rossinna77Github"
    type: vless
    server: "45.198.87.113"
    port: 8443
    uuid: "7896c501-248f-4068-bc2f-363c91ba5122"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "storage.yandex.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7zd9mJilgjOrg_ohtw23Vmio-pdnYqeP_r-kiWt87Cg"
      short-id: "2715592069f36fe7"
  - name: "@rossinna77Github"
    type: vless
    server: "104.17.54.45"
    port: 2096
    uuid: "a52ebda5-cf07-495f-831c-3f7995135e48"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nova-coral-core-c091.infinityconfig8.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?u=dd4ffbed10"
      headers:
        Host: "nova-coral-core-c091.infinityconfig8.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "45.195.137.243"
    port: 8443
    uuid: "7f89560c-b9f0-4c56-b3e0-1b1bdafe0b08"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "storage.yandex.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "IdqrygjwHBEMCOamBl7a504TVk6uMAtTRj0xLWcFcxY"
      short-id: "e3d38cee79d4f94c"
  - name: "@rossinna77Github"
    type: vless
    server: "162.159.10.87"
    port: 443
    uuid: "eeb6823c-b926-4ea2-866a-5542edd26e59"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "t1s1.rittbo.kdns.fr"
    network: ws
    ws-opts:
      path: "/fp=chrome"
      headers:
        Host: "t1s1.rittbo.kdns.fr"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
