name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime36.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "afb13fa2-bba2-417f-b8c2-62565f92a78d"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "orange-block-5cd1.124-199.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bf667068-11cb-4c37-a867-4a2b03b45555"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "flat-sun-b8d3.225-154.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "6ce18ff9-1c38-4ffc-bf07-3bc97acb5e09"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "itunes.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HWUNFHoOryJHQXKF-ZOm6wMYZdVJwH5aHGa5I9_HDGA"
      short-id: "dfa28122"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b85b1e90-b5ed-0002-b433-bf9d2eca0e42"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "ru9.aimodelhub.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jwT3lcIzJQMjzBKRNsmyRGrgaa1qNfE7pQF_nAKu0GA"
      short-id: "a73cf719b624"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "FH72359861"
    sni: "summary-lemming.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f32b0ea8-5b9f-4ee2-b20c-0bdfd2057e1d"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "throbbing-shape-b190.478-57a.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e1588d14-0a16-483f-9d54-cf521541035b"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.apple.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "GYD0NwdNDlDIAkRGIMqRC7RuhZTScmSw2SlknoRNrDo"
      short-id: "521959f62377e2fa"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "FH72359861"
    sni: "champion-panther.rooster465.autos"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "f6e14309-5cff-4f5d-bce1-06a260159bbe"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "steep-bread-32f0.92-d12.workers.dev"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "PQ05174892"
    sni: "wise-rhino.rooster465.autos"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "cf39cbf2-8926-43b5-ba3e-45b975019094"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=proxyip.us.cmliussss.net"
      headers:
        Host: "snowy-feather-39d3.428.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bf380279-cbd5-4e55-96d1-f5a652aaf6b3"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
