name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "79aa80da-2394-4b0a-986b-15dad2382046"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5659b42c-636f-4563-ac41-87d565d0dd1e"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.autumniussss.net"
      headers:
        Host: "autumn-base-0eb9.116-d25.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "0b41f339-5809-46ef-8351-b03fdc441539"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "FpoiXF69hQT3E6d4URTB.MamADNEIZeH.WorKers.DEV"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/vl/lYNtP7z8pJUmfp01tz5wEnuDujJtZ?ed=2560"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a5c7e18f-1701-46ed-8f42-00eb078d9445"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=proxyip.kr.cmliussss.net"
      headers:
        Host: "weathered-snow-b87b.292-455.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "10fd5cba-3daa-432b-aa47-8143820656a3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3t1yvbyla-rj740g.28m7r63dttya6gazmhoo.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "3t1yvbyla-rj740g.28m7r63dttya6gazmhoo.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "blackshadow.dpdns.org"
    network: ws
    ws-opts:
      path: "/44.209.52.7-443"
      headers:
        Host: "blackshadow.dpdns.org"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "129b50b6-060d-475c-b1de-b87c2a67051f"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "shrill-waterfall-bfe2.416.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "4212034d-c18b-4060-b218-4f8372e5473a"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "summer-hill-7f65.275-521.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bbecfa92-4f64-4eb8-82e6-388394d909fe"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5bbf0601-8431-45f6-a4e9-a1e8b44c0055"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "misty-mouse-141d.177-f18.workers.dev"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "beed721d-73b6-47fc-a7b0-cac10e624b98"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
